name: Dependency Submission

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          distribution: temurin
          java-version: 17
      - name: Submit Dependency Snapshot
        uses: advanced-security/maven-dependency-submission-action@v3
